"""
ChildGuard AI - Windows SafeSearch & Loopback DNS Enforcer
Enforces network-level search engine SafeSearch VIPs and sinks blacklisted domains to loopback.
"""

import os
import sys
import ctypes
import time
import threading

dnsapi = ctypes.windll.dnsapi

# Windows Hosts File Path
HOSTS_FILE_PATH = r"C:\Windows\System32\drivers\etc\hosts"

# ChildGuard Block Demarcation Tags
TAG_START = "# === CHILDGUARD SAFESEARCH RULES START ==="
TAG_END = "# === CHILDGUARD SAFESEARCH RULES END ==="

# Official Search Engine SafeSearch VIP Addresses
GOOGLE_SAFESEARCH_IP = "216.239.38.120"   # forcesafesearch.google.com
YOUTUBE_RESTRICTED_IP = "216.239.38.119"  # restrict.youtube.com
BING_STRICT_IP = "204.79.197.220"         # strict.bing.com
DUCKDUCKGO_SAFE_IP = "52.142.124.215"     # safe.duckduckgo.com
NULL_LOOPBACK_IP = "127.0.0.1"

# SafeSearch Domain Routing Map
SAFESEARCH_MAP = {
    GOOGLE_SAFESEARCH_IP: [
        "www.google.com", "google.com",
        "www.google.co.in", "google.co.in",
        "www.google.co.uk", "google.co.uk",
        "www.google.ca", "google.ca"
    ],
    YOUTUBE_RESTRICTED_IP: [
        "www.youtube.com", "youtube.com",
        "m.youtube.com", "youtubei.googleapis.com"
    ],
    BING_STRICT_IP: [
        "www.bing.com", "bing.com"
    ],
    DUCKDUCKGO_SAFE_IP: [
        "duckduckgo.com", "www.duckduckgo.com"
    ]
}

# Domain Sinkhole Blacklist (High-Risk Adult, Gambling, Piracy)
SINKHOLE_DOMAINS = [
    "pornhub.com", "www.pornhub.com",
    "xvideos.com", "www.xvideos.com",
    "xnxx.com", "www.xnxx.com",
    "redtube.com", "www.redtube.com",
    "bet365.com", "www.bet365.com",
    "stake.com", "www.stake.com",
    "1xbet.com", "www.1xbet.com",
    "pokerstars.com", "www.pokerstars.com",
    "thepiratebay.org", "www.thepiratebay.org",
    "1337x.to", "www.1337x.to",
    "yts.mx", "www.yts.mx"
]

def flush_dns_cache() -> bool:
    """Calls Win32 DnsFlushResolverCache to flush DNS immediately without restart."""
    try:
        res = dnsapi.DnsFlushResolverCache()
        return bool(res)
    except Exception as e:
        print(f"[DNS Filter] Failed to flush DNS resolver cache: {e}")
        return False

def generate_rules_block() -> str:
    """Generates the atomic ChildGuard rules text block."""
    lines = [TAG_START, "# Automatically generated by ChildGuard Protection Daemon. Do not edit."]
    
    # SafeSearch VIPs
    for ip, domains in SAFESEARCH_MAP.items():
        for d in domains:
            lines.append(f"{ip.ljust(16)} {d}")
            
    # Sinkhole Blacklist
    lines.append(f"# High-Risk Domain Sinkhole")
    for d in SINKHOLE_DOMAINS:
        lines.append(f"{NULL_LOOPBACK_IP.ljust(16)} {d}")
        
    lines.append(TAG_END)
    return "\n".join(lines) + "\n"

class SafeSearchEnforcer:
    def __init__(self, hosts_path: str = HOSTS_FILE_PATH):
        self.hosts_path = hosts_path
        self.stop_requested = False
        self.watchdog_thread = None

    def apply_rules(self) -> bool:
        """Injects ChildGuard rules into the hosts file cleanly."""
        try:
            current_content = ""
            if os.path.exists(self.hosts_path):
                with open(self.hosts_path, "r", encoding="utf-8", errors="ignore") as f:
                    current_content = f.read()

            # Strip existing block if present
            cleaned_content = self._strip_childguard_block(current_content)
            new_block = generate_rules_block()
            final_content = cleaned_content.rstrip() + "\n\n" + new_block

            with open(self.hosts_path, "w", encoding="utf-8") as f:
                f.write(final_content)

            flush_dns_cache()
            print("[DNS Filter] ChildGuard SafeSearch & Domain Sinkhole rules activated.")
            return True
        except PermissionError:
            print("[DNS Filter] Notice: Administrator privileges required to write to system hosts file.")
            return False
        except Exception as e:
            print(f"[DNS Filter] Error applying rules: {e}")
            return False

    def remove_rules(self) -> bool:
        """Restores original hosts file removing ChildGuard block."""
        try:
            if not os.path.exists(self.hosts_path):
                return True
            with open(self.hosts_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

            cleaned = self._strip_childguard_block(content)
            with open(self.hosts_path, "w", encoding="utf-8") as f:
                f.write(cleaned)

            flush_dns_cache()
            print("[DNS Filter] ChildGuard SafeSearch rules cleanly restored.")
            return True
        except Exception as e:
            print(f"[DNS Filter] Error restoring hosts: {e}")
            return False

    def _strip_childguard_block(self, text: str) -> str:
        if TAG_START in text and TAG_END in text:
            before = text.split(TAG_START)[0]
            after = text.split(TAG_END)[1]
            return before.rstrip() + "\n" + after.lstrip()
        return text

    def verify_and_heal(self):
        """Self-healing anti-tamper check to ensure rules remain intact."""
        try:
            if not os.path.exists(self.hosts_path):
                self.apply_rules()
                return

            with open(self.hosts_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

            if TAG_START not in content or TAG_END not in content:
                print("[DNS Filter Anti-Tamper] Rules were modified! Healing now...")
                self.apply_rules()
        except Exception:
            pass

    def start_watchdog(self, interval_seconds: int = 30):
        """Runs periodic self-healing anti-tamper verification."""
        def run_loop():
            while not self.stop_requested:
                time.sleep(interval_seconds)
                self.verify_and_heal()

        self.watchdog_thread = threading.Thread(target=run_loop, daemon=True)
        self.watchdog_thread.start()

    def stop_watchdog(self):
        self.stop_requested = True
